services:
    ipxe:
        build:
            context: .
            args:
                IPXE_TAG: ${IPXE_TAG}
        image: ipxe-builder:${IPXE_TAG}
        command:
            - bin/ipxe.lkrn
        volumes:
            - ./out:/out:rw
            - ./options:/ipxe/src/config/custom:ro
